### ISSUE TITLE
category name with white spaces return an error

### ISSUE THREAD

**Issue by managai** [tomwalker/django_quiz#46]
creating a new category with spaces retunr an error

Exception Type: 	NoReverseMatch
Exception Value: 	Reverse for 'quiz_category_list_matching' with arguments '()' and keyword arguments '{'category_name': 'Il corso degli eventi'}' not found. 1 pattern(s) tried: ['it/category/(?P<category_name>[\\w.-]+)/$']

quiz/templates/quiz/category_list.html, error at line 11
<a href=" {% url 'quiz_category_list_matching' category_name=cat.category %} "></a>

a solution should be to have 3 fields in quiz_category DB:
* id
* name
* label
where name acts like url-friendly url for wordpress posts (the url is build in lowercase and whitespaces are replaced by - char)
name should be automatically suggested as in wordpress

**Comment by sjardim** [comment]
I've manage to get it work by changing the following url regex:

quiz/urls.py

from:
`url(regex=r'^category/(?P<category_name>[\w.-]+)/$'`
to:
`url(regex=r'^category/(?P<category_name>[\w|\W-]+)/$'`

You can test it here:
http://www.pyregex.com/?id=eyJyZWdleCI6IihbXFx3fFxcV10rKSIsImZsYWdzIjowLCJtYXRjaF90eXBlIjoibWF0Y2giLCJ0ZXN0X3N0cmluZyI6ImFyZWEgZGUgY29uaGVjaW1lbnRvIn0%3D
