### ISSUE TITLE
fr-FR locale

### ISSUE THREAD

**Issue by pikpoket** [tomwalker/django_quiz#89]
Hello,

I've translated .po files for "fr-FR", but I don't really know how to merge them in the project. I don't even managed to use them on my personnal project.

I join them in this issue so a good samaritan may success where I failed.
I don't care about any attributions.

[fr-FR_po_files.zip](https://github.com/tomwalker/django_quiz/files/3570011/fr-FR_po_files.zip)

**Comment by tomwalker** [comment]
Thank you!

I have been planning to update this project so I will include the
translations.
